unique_ids:
  assets:
    standard-page.html: IUEZV7IKLWL6XZVB53WDD7VTW54H6WU2
    theme.css: JQMM52PTSWB3R5Q2PDZPKQ7LQPQ6BZDA
  forms:
    Form1: KJP7FU4J3R75JLK2LA5FPH7P5BZUOF5O
  modules: {}
  scripts: {}
  server_modules: {}
